// SPDX-License-Identifier: Apache-2.0
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';

const NL = String.fromCharCode(10);

// Build an MCP tool result: an array of text content blocks, with an optional
// top-level isError flag so clients can distinguish a failure from a result.
export function textResult(payload, { isError = false } = {}) {
  const text = typeof payload === 'string' ? payload : JSON.stringify(payload, null, 2);
  return { content: [{ type: 'text', text }], ...(isError ? { isError: true } : {}) };
}

async function fetchTool(name, deps, apiPath, params) {
  try {
    return textResult(await deps.client.get(apiPath, { params }));
  } catch (err) {
    return textResult(name + ' failed: ' + (err && err.message ? err.message : err), { isError: true });
  }
}

function connectorExportName(name) {
  const words = String(name).replace(/[^a-zA-Z0-9_$]+/g, ' ').split(' ').filter(Boolean);
  let camel = words.map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1))).join('');
  if (!camel) camel = 'connector';
  if (/^[0-9]/.test(camel)) camel = 'c' + camel;
  return camel + 'Connector';
}

function apiTemplate({ name, endpoint }) {
  const exportName = connectorExportName(name);
  const url = endpoint || 'https://example.com/data.json';
  return [
    '// SPDX-License-Identifier: Apache-2.0',
    '// ' + name + ' connector - generated by philotas-mcp scaffold_connector.',
    '// Kind: api. Point url at an upstream endpoint and implement normalize to',
    '// map the response to GeoJSON features. See lib/connectors/define.js.',
    '',
    "import { defineConnector, apiPull } from '../lib/connectors/define.js';",
    '',
    'export const ' + exportName + ' = defineConnector({',
    '  id: ' + "'" + name + "'" + ',',
    '  label: ' + "'" + name + ' (api)' + "'" + ',',
    "  kind: 'api',",
    '  ttl: 60_000,',
    "  layer: { color: '#9ca3af', type: 'circle', radius: 5 },",
    '  render: (p) => [["title", p.title], ["source", ' + "'" + name + "'" + ']],',
    '  pull: apiPull({',
    '    url: () => ' + JSON.stringify(url) + ',',
    '    normalize: (data, region) => {',
    '      // Return an array of GeoJSON features, each with geometry and properties:',
    "      //   { type: 'Feature', geometry: { type: 'Point', coordinates: [lon, lat] }, properties: { ... } }",
    '      return [];',
    '    },',
    '  }),',
    '});',
    '',
  ].join(NL);
}

function datalakeTemplate({ name, endpoint }) {
  const exportName = connectorExportName(name);
  return [
    '// SPDX-License-Identifier: Apache-2.0',
    '// ' + name + ' connector - generated by philotas-mcp scaffold_connector.',
    '// Kind: datalake. Implement query to return rows and toFeature to map a row',
    '// to a GeoJSON feature. See lib/connectors/define.js.',
    '',
    "import { defineConnector, datalakePull } from '../lib/connectors/define.js';",
    '',
    'export const ' + exportName + ' = defineConnector({',
    '  id: ' + "'" + name + "'" + ',',
    '  label: ' + "'" + name + ' (datalake)' + "'" + ',',
    "  kind: 'datalake',",
    '  ttl: 600_000,',
    "  layer: { color: '#9ca3af', type: 'circle', radius: 5 },",
    '  render: (p) => [["title", p.title], ["source", ' + "'" + name + "'" + ']],',
    '  pull: datalakePull({',
    '    query: async (region) => {',
    '      // Return rows from your lake, e.g. [{ name, lon, lat, ... }].',
    '      return [];',
    '    },',
    '    toFeature: (row) => ({',
    "      type: 'Feature',",
    "      geometry: { type: 'Point', coordinates: [row.lon, row.lat] },",
    '      properties: { layer: ' + "'" + name + "'" + ', title: row.name },',
    '    }),',
    '  }),',
    '});',
    '',
  ].join(NL);
}

function findConnector(mod) {
  if (mod.default && mod.default.id && typeof mod.default.pull === 'function') return mod.default;
  for (const value of Object.values(mod)) {
    if (value && value.id && typeof value.pull === 'function') return value;
  }
  return null;
}

async function scaffoldConnector(args, deps) {
  if (!args.name) return textResult('scaffold_connector requires a "name" argument', { isError: true });
  if (!args.kind) return textResult('scaffold_connector requires a "kind" argument ("api" or "datalake")', { isError: true });
  if (args.kind !== 'api' && args.kind !== 'datalake') return textResult('scaffold_connector kind must be "api" or "datalake"', { isError: true });
  if (!/^[a-zA-Z0-9_-]+$/.test(args.name)) return textResult('scaffold_connector name must be a simple slug (letters, digits, - or _)', { isError: true });
  const cwd = deps.cwd || process.cwd();
  const dir = path.join(cwd, 'connectors');
  const filePath = path.join(dir, args.name + '.js');
  const template = args.kind === 'datalake' ? datalakeTemplate(args) : apiTemplate(args);
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(filePath, template, 'utf8');
  } catch (err) {
    return textResult('scaffold_connector failed to write ' + filePath + ': ' + (err && err.message ? err.message : err), { isError: true });
  }
  return textResult({ name: args.name, kind: args.kind, endpoint: args.endpoint || null, path: filePath, written: true });
}

async function validateConnector(args, deps) {
  if (!args.path) return textResult('validate_connector requires a "path" argument', { isError: true });
  const cwd = deps.cwd || process.cwd();
  const resolved = path.resolve(cwd, args.path);
  let mod;
  try {
    mod = await import(pathToFileURL(resolved).href + '?t=' + Date.now());
  } catch (err) {
    return textResult({ valid: false, path: resolved, reason: 'import failed: ' + (err && err.message ? err.message : err) });
  }
  const connector = findConnector(mod);
  if (!connector) {
    return textResult({ valid: false, path: resolved, reason: 'no connector found (expected an export with an id and a pull() function)' });
  }
  let result;
  try {
    result = await connector.pull();
  } catch (err) {
    return textResult({ valid: false, path: resolved, connector: connector.id, reason: 'pull() threw: ' + (err && err.message ? err.message : err) });
  }
  if (!result || result.type !== 'FeatureCollection' || !Array.isArray(result.features)) {
    return textResult({ valid: false, path: resolved, connector: connector.id, reason: 'pull() did not return a GeoJSON FeatureCollection with a features array' });
  }
  const features = result.features.filter((f) => f && f.type === 'Feature' && f.geometry);
  return textResult({ valid: true, path: resolved, connector: connector.id, kind: connector.kind, features: features.length, total: result.features.length });
}

function countSummary(text, label) {
  const re = new RegExp('# ' + label + ' ([0-9]+)', 'g');
  let last = 0;
  let m;
  while ((m = re.exec(text)) !== null) last = Number(m[1]);
  return last;
}

async function runTests(args, deps) {
  const cwd = deps.cwd || process.cwd();
  const spawnImpl = deps.spawnImpl || spawn;
  const output = await new Promise((resolve) => {
    const child = spawnImpl(process.execPath, ['--test', '--test-reporter=tap'], { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    let err = '';
    if (child.stdout && child.stdout.on) child.stdout.on('data', (d) => (out += d));
    if (child.stderr && child.stderr.on) child.stderr.on('data', (d) => (err += d));
    child.on('error', (e) => resolve({ error: e.message, out, err }));
    child.on('close', (code) => resolve({ code, out, err }));
  });
  const text = (output.out || '') + (output.err || '');
  if (output.error) {
    return textResult({ ok: false, error: output.error, pass: 0, fail: 0, total: 0 });
  }
  const pass = countSummary(text, 'pass');
  const fail = countSummary(text, 'fail');
  const total = countSummary(text, 'tests');
  return textResult({ ok: output.code === 0 && fail === 0, exitCode: output.code, pass, fail, total });
}

export function createHandlers(deps = {}) {
  return {
    philotas_status: async (args) => fetchTool('philotas_status', deps, '/api/status'),
    philotas_regions: async (args) => fetchTool('philotas_regions', deps, '/api/regions'),
    philotas_feed: async (args) => {
      if (!args.feed) return textResult('philotas_feed requires a "feed" argument', { isError: true });
      return fetchTool('philotas_feed', deps, '/api/feeds/' + encodeURIComponent(args.feed), { region: args.region });
    },
    philotas_graph: async (args) => fetchTool('philotas_graph', deps, '/api/graph', { region: args.region }),
    philotas_search: async (args) => {
      if (!args.query) return textResult('philotas_search requires a "query" argument', { isError: true });
      return fetchTool('philotas_search', deps, '/api/search', { q: args.query, region: args.region });
    },
    philotas_alerts: async (args) => fetchTool('philotas_alerts', deps, '/api/alerts', { region: args.region }),
    philotas_detections: async (args) => fetchTool('philotas_detections', deps, '/api/detections', { region: args.region }),
    scaffold_connector: async (args) => scaffoldConnector(args, deps),
    validate_connector: async (args) => validateConnector(args, deps),
    run_tests: async (args) => runTests(args, deps),
  };
}

export const TOOLS = [
  { name: 'philotas_status', title: 'Philotas status', description: 'Deployment and per-feed health for the configured Philotas deployment.', inputSchema: {} },
  { name: 'philotas_regions', title: 'Philotas regions', description: 'List the available regions.', inputSchema: {} },
  { name: 'philotas_feed', title: 'Philotas feed', description: 'Normalized GeoJSON for one feed, optionally region-scoped.', inputSchema: { feed: { type: 'string', required: true, description: 'Feed id' }, region: { type: 'string', required: false, description: 'Region id' } } },
  { name: 'philotas_graph', title: 'Philotas graph', description: 'Entities and resolved relationships for a region.', inputSchema: { region: { type: 'string', required: false, description: 'Region id' } } },
  { name: 'philotas_search', title: 'Philotas search', description: 'Full-text search across a region live entities.', inputSchema: { query: { type: 'string', required: true, description: 'Search text' }, region: { type: 'string', required: false, description: 'Region id' } } },
  { name: 'philotas_alerts', title: 'Philotas alerts', description: 'Entities matching active rules plus detection-workflow runs for a region.', inputSchema: { region: { type: 'string', required: false, description: 'Region id' } } },
  { name: 'philotas_detections', title: 'Philotas detections', description: 'Recent stored detections, optionally region-scoped.', inputSchema: { region: { type: 'string', required: false, description: 'Region id' } } },
  { name: 'scaffold_connector', title: 'Scaffold connector', description: 'Write a connector template file into connectors/<name>.js in the working directory.', inputSchema: { name: { type: 'string', required: true, description: 'Connector name (slug)' }, kind: { type: 'enum', values: ['api', 'datalake'], required: true, description: 'Connector kind' }, endpoint: { type: 'string', required: false, description: 'Upstream endpoint URL (api kind)' } } },
  { name: 'validate_connector', title: 'Validate connector', description: 'Import a connector file, run its pull(), and report whether it returns GeoJSON features.', inputSchema: { path: { type: 'string', required: true, description: 'Path to the connector file' } } },
  { name: 'run_tests', title: 'Run tests', description: 'Run node --test in the project root and report pass/fail counts.', inputSchema: {} },
];
